export const FETCH_START = 'FETCH_START'
export const FETCH_SUCCSESS = 'FETCH_SUCCSESS'
export const FETCH_ERROR = 'FETCH_ERROR'

export const ADD_OFFSET = 'ADD_OFFSET'
export const FILTER_POKEMONS = 'FILTER_POKEMONS'

export const ADD_FAVORITE = 'ADD_FAVORITE'
